[package]
name = "rs-eip-adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
byteorder = "1"
anyhow = "1"
log = "0.4"
env_logger = "0.10"
